### ISSUE TITLE
Shorten image-2x mixin's media query

### ISSUE THREAD

**Issue by HugoGiraudel** [gillesbertaux/andy#11]
The media query coult be shortened based on https://github.com/kaelig/hidpi/blob/master/_hidpi.scss#L37.

**Comment by gillesbertaux** [comment]
Hm, I'm not sure, could you maybe explain it a little bit?

**Comment by HugoGiraudel** [comment]
I feel like you are using too many prefixes for this; some are unnecessary. :)

**Comment by mknadler** [comment]
Based on http://caniuse.com/#feat=css-media-resolution, it looks like all that is necessary for good browser coverage is:
1. -webkit-min-device-pixel-ratio for Safari, iOS Safari, Android <= 4.3, and Blackberry.
2. dpi for IE 9 through IE 11
3. dpx for everything else

**Comment by gillesbertaux** [comment]
Merged on #22. Closing.
