### ISSUE TITLE
Shadows, radius and prefixes

### ISSUE THREAD

**Issue by HugoGiraudel** [gillesbertaux/andy#13]
`border-radius` and `box-shadow` probably don't need vendor prefixes anymore.

**Comment by mknadler** [comment]
verified: 
http://caniuse.com/#search=border-radius
http://caniuse.com/#search=box-shadow

Looks like *no* recent versions of *any* major browser needs prefixes for either.

**Comment by mknadler** [comment]
In fact, as both of these have shorthands baked in (e.g. `border-radius: 3px 2px 2px 3px`), and everything that `@mixin shadow`, `@mixin border` (see #8 ), and `@mixin border-radius` do are already a part of vanilla CSS3, I think those three could all be safely deprecated?

**Comment by gillesbertaux** [comment]
Agreed.

**Comment by gillesbertaux** [comment]
This should be removed too then: `@mixin border-radius-separate($topLeftRadius, $topRightRadius, $bottomLeftRadius, $bottomRightRadius)`

**Comment by gillesbertaux** [comment]
To sum up, let's remove:
- `@mixin border-radius-separate``
- `@mixin shadow` (or maybe simplify it for the inset?)
- `@mixin border-radius`

**Comment by HugoGiraudel** [comment]
All removed at this point.
