### ISSUE TITLE
Consider SassDoc comments

### ISSUE THREAD

**Issue by HugoGiraudel** [gillesbertaux/andy#16]
To document the public API. :)

**Comment by mknadler** [comment]
@gillesbertaux, if you want any help getting SassDoc set up, I recently did this (after @HugoGiraudel opened an identical issue on one of my repos :P); would be happy to help out!

**Comment by gillesbertaux** [comment]
Yep, good call. Next noteworthy milestone. 

Let's clean up Andy and close all the current issues first and then let's open an issue for that.

**Comment by HugoGiraudel** [comment]
PR pending: #21.

**Comment by gillesbertaux** [comment]
Merged! :shipit:
