### ISSUE TITLE
@mixin ine-height produces inconsistent results

### ISSUE THREAD

**Issue by mknadler** [gillesbertaux/andy#7]
@mixin line-height($heightValue: 12 ){
        line-height: $heightValue + px; //fallback for old browsers
        line-height: (0.125 * $heightValue) + rem;
    }

Even if one assumes `body { font-size: 16px ;}` (which we shouldn't), and `@mixin line-height` is called with the default value, as in `@include line-height;`,  this mixin spits out `line-height: 12px` = `12px` for pixels, and `line-height: 1.5rem` = `24px` for rems. The 0.125 is supposed to be a hardcoded representation of a 16px root font size, right? If so, shouldn't it be `0.0625`?

There are a few options on how to proceed:

1 - Change the mixin to assume a hardcoded 16px base font size:
         
    @mixin line-height($heightValue: 12){
        line-height: $heightValue + px; //fallback for old browsers
        line-height: (0.0625 * $heightValue) + rem;
    }

2 - Change the mixin to dynamically use a base-font-size variable, like `@mixin fontsize` does:

    @mixin line-height($heightValue: 12){
        $base-font-size: 16px !default;
        line-height: $heightValue + px; //fallback for old browsers
        line-height: ( 1 / ( $base-font-size / ($base-font-size * 0 + 1) ) * $heightValue + rem );
    }

3 - Option 2, except the base-font-size a global variable, in a 'settings' section at the top of the file, for use in both `@mixin line-height` and `@mixin fontsize`. I think this is my preferred option -- it's the DRYest of the three.

    $base-font-size: 16px !default;

    @mixin line-height($heightValue: 12){
        line-height: $heightValue + px; //fallback for old browsers
        line-height: ( 1 / ( $base-font-size / ($base-font-size * 0 + 1) ) * $heightValue + rem );
    }

There are other ways to deal with settings -- I think Susy has the most elegant solution -- but something like 3 would probably suffice here.

**Comment by gillesbertaux** [comment]
Hey @mknadler! 

Sorry for the late answer w/ the holidays and all. I will take care of it later next week or this WE, just started a new job this week so it's kind of hard to focus on Andy right now. I'll get back to you next week, thanks!

**Comment by mknadler** [comment]
happy holidays :)

**Comment by gillesbertaux** [comment]
Hi @mknadler ! I just read your comments:
- Agreed on the single file + settings at the top of the file. 1/ Having another file sounds like an overkill to me. 2/ I would like Andy to become a coherent system which seems more developer friendly than just pick mixins here and there (which is still feasible btw). 
- We should definitely standardize name consistency.
- Ok with your explanation let's go with your solution then. 

What I will implement in the next few days:
- [ ] Naming convention, let's go with lower-case-hyphenated
- [ ] Add settings at the top of the file w/ $base-font
- [ ] Modify mixins accordingly

Missing anything?

**Comment by gillesbertaux** [comment]
Changes added + new release. Let's re-open an issue to discuss what's missing.
