### ISSUE TITLE
Normalize naming conventions

### ISSUE THREAD

**Issue by HugoGiraudel** [gillesbertaux/andy#9]
Some arguments use camelCase, some are hyphenated. Since CSS is an hyphenated language, I suggest going hyphens all the way.

**Comment by gillesbertaux** [comment]
:+1:  Alright. I'll check the current pull requests and check afterwards if there's any camelCase remaining.

**Comment by HugoGiraudel** [comment]
Looks like @mknadler is on fire. :)

**Comment by gillesbertaux** [comment]
:godmode: :activated
